on: 
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run compile
      if: runner.os == 'Linux'
    - name: Merge into develop
      uses: Goobles/gh-actions-merge-command@v1
      with:
        user_name: Attilio Capocchiani
        user_email: attilio.capocchiani@gmail.com
        allow_ff: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
