on: 
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run compile
      if: runner.os == 'Linux'
    - name: Merge into develop
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        target_branch: 'develop'
        github_token: ${{ github.token }}
      env:
        github.token: ccacbe3fec44293631c1ce5634f354ac7ed45316
