on: 
  pull_request:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
    - name: Merge by labeled
      uses: devmasx/merge-branch@v1.3.1
      with:
        label_name: 'merged in develop'
        target_branch: 'develop'
        github_token: ${{ github.token }}
      env:
        github.token: ccacbe3fec44293631c1ce5634f354ac7ed45316
